const shopActionType = {
    // UPDATE_COLLECTIONS:'UPDATE_COLLECTIONS'
    // ----------React Thunk 
    FETCH_COLLECTION_START:'FETCH_COLLECTION_START',
    FETCH_COLLECTION_SUCCESS: 'FETCH_COLLECTION_SUCCESS',
    FETCH_COLLECTION_FAIL:'FETCH_COLLECTION_FAIL'

}


export default shopActionType